print(" 1. O médico bate no seu joelho (no tendão patelar) com um martelinho de borracha para examinar seus")
resposta1 = input("")
while resposta1 != "movimentos":
    print("   ")
    print("#"*20)
    print("#  Resposta errada #")
    print("#"*20)
    print("   ")
    print("Digite 1 para 'verifique a resposta' ")
    print("Digite 2 para 'tente novamente' ")
    resposta1 = input("")
print("Correto. Muito bem!")
print("2. Quando os reflexos estão normais a perna __________ à  batida no joelho com um movimento (o chamado reflexo patelar).")
resposta2 = input("")
while resposta2 != "responde":
    print("   ")
    print("#"*20)
    print("#  Resposta errada #")
    print("#"*20)
    print("   ")
    print("Digite 1 para 'verifique a resposta' ")
    print("Digite 2 para 'tente novamente' ")
    resposta2 = input("")
print("Correto. Muito bem!")
print("3. O movimento da perna ou reflexo patelar é uma resposta à batida do martelo no joelho.")
resposta3 = input("")
while resposta3 != "resposta":
    print("   ")
    print("#"*20)
    print("#  Resposta errada #")
    print("#"*20)
    print("   ")
    print("Digite 1 para 'verifique a resposta' ")
    print("Digite 2 para 'tente novamente' ")
    resposta3 = input("")
print("Correto. Muito bem!")
print("4.O objeto estimulador que o médico usa para provocar o movimento é o ")
resposta4 = input("")
while resposta4 != "martelo":
    print("   ")
    print("#"*20)
    print("#  Resposta errada #")
    print("#"*20)
    print("   ")
    print("Digite 1 para 'verifique a resposta' ")
    print("Digite 2 para 'tente novamente' ")
    resposta4 = input("")
print("Correto. Muito bem!")
print("5.O estí­mulo que elicia (provoca) o movimento da perna é a  ")
resposta5 = input("")
while resposta5 != "batida":
    print("   ")
    print("#"*20)
    print("#  Resposta errada #")
    print("#"*20)
    print("   ")
    print("Digite 1 para 'verifique a resposta' ")
    print("Digite 2 para 'tente novamente' ")
    resposta5 = input("")
print("com o objeto estimulador ou martelo.")
print("Correto. Muito bem!")
print("6.No reflexo patelar chamamos a batida ou golpe de ")
resposta6 = input("")
while resposta6 not in ("estímulo","estimulo"):
    print("   ")
    print("#"*20)
    print("#  Resposta errada #")
    print("#"*20)
    print("   ")
    print("Digite 1 para 'verifique a resposta' ")
    print("Digite 2 para 'tente novamente' ")
    resposta6 = input("")
print("Correto. Muito bem!")
print("Preencha as outras lacunas")
print("e o martelinho de borracha que a desfere de objeto... ")
resposta6a = input("")
while resposta6a != "":
    print("   ")
    print("#"*20)
    print("#  Resposta errada #")
    print("#"*20)
    print("   ")
    print("Digite 1 para 'verifique a resposta' ")
    print("Digite 2 para 'tente novamente' ")
    resposta6a = input("")
print("Correto. Muito bem!")
print("Para visualizar a continuação, acesse: https://www.ufrgs.br/psicoeduc/maquina-de-ensinar/")
